### ISSUE TITLE
Some floating point numbers are parsed with rounding errors

### ISSUE THREAD

**Issue by jarek-foksa** [progers/pathseg#11]
For example 2.163 in  d="M 0 0 L 100 2.163" is parsed as 2.1630000000000003. I managed to work around this bug by changing three lines: https://github.com/jarek-foksa/path-data-polyfill.js/commit/423ca79b98c39120cda5c7ea9fa7bd821780d303

**Comment by progers** [comment]
Thanks for the report @jarek-foksa!

Your approach definitely works but it's a little slow to grow a vector for each decimal. I just committed https://github.com/progers/pathseg/commit/f940db56d2e285be4aacd1944c08a3b6c16b14c0 which should have the same effect by just reorganizing how the arithmetic works. Would you be up for reviewing my change to see if you notice any bugs?

**Comment by progers** [comment]
(Apologies for the glacial response time. Just got back from a one month trip to China where I was off the grid.)

**Comment by jarek-foksa** [comment]
Thanks for fixing this. I have tested the parser with a really large path (1290 segments, each segment using numbers with 6 decimal places). With my changes it took ~10ms longer to parse that path, your solution does not seem to impact performance in noticeable way.
