### ISSUE TITLE
Global Context when creating variables

### ISSUE THREAD

**Issue by tigermarques** [progers/pathseg#13]
When creating variables like SVGPathSeg or SVGPathSegClosePath, the namespace window is correctly being used, so that the functions are created in the correct context.
However, on the same code, properties for these variables do not use the window namespace, which means that a global variable will be accessed instead. When running on the browser, this works fine, since window is the global context for the application. But in other contexts this throws an exception since variables like SVGPathSegClosePath do not exist in the global context.

My use case is running mocha unit tests on an application that depends on pathseg, and these tests can't run since the plugin can't be initialized

**Comment by progers** [comment]
Ahh, I see what you mean. Would you be willing to submit a pull request to fix it?

**Comment by tigermarques** [comment]
Yeah sure, i'll look into it

**Comment by tigermarques** [comment]
Pull request submitted.

**Comment by tigermarques** [comment]
Closing since pull request was already accepted
