### ISSUE TITLE
removeItem  API is No effect

### ISSUE THREAD

**Issue by Einsy** [progers/pathseg#16]
**removeItem  API is No effect**
 **chrome 54.0.2840.71 m**

{
  "name": "pathseg",
  "version": "1.0.2",
  "description": "A polyfill for SVG's SVGPathSeg and SVGPathSegList",
  "main": "pathseg.js",
  "directories": {
    "test": "tests"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/progers/pathseg.git"
  },
  "author": "Philip Rogers",
  "license": "Chromium's License",
  "bugs": {
    "url": "https://github.com/progers/pathseg/issues"
  },
  "homepage": "https://github.com/progers/pathseg",
  "keywords": [
    "SVG",
    "polyfill",
    "pathseg",
    "SVGPathSeg",
    "SVGPathSegList"
  ]
}

**Comment by progers** [comment]
Hi Einsy, can you help me understand this bug? How can I reproduce it?

**Comment by progers** [comment]
Closing as there was no feedback about how to reproduce this. Happy to reopen if there is more information.
