### ISSUE TITLE
SVGPathElement is used before being defined

### ISSUE THREAD

**Issue by vitorbaptista** [progers/pathseg#19]
See https://github.com/progers/pathseg/blob/a1072a7bfbb3f45d70fa3d783bb710537ba7974c/pathseg.js#L314-L334

All other attributes follow the pattern of defining `window.ATTRIBUTE_NAME` and then changing `window.ATTRIBUTE_NAME.prototype`, except (as far as I could see) `SVGPathElement`. This causes an error to be thrown, as we're in strict mode which disallows using variables before defining them.

**Comment by progers** [comment]
Thanks for reporting this issue. Is this a new bug in 1.1.0 or did it exist before? Can you describe a way for me to reproduce this issue?

**Comment by vitorbaptista** [comment]
@progers I think the simplest way to reproduce it is:

```
$ node -e "window = {}; require('./pathseg');"
/home/vitor/Projetos/pathseg/pathseg.js:316
        window.SVGPathElement.prototype.createSVGPathSegClosePath = function() { return new window.SVGPathSegClosePath(undefined); }
                             ^

TypeError: Cannot read property 'prototype' of undefined
    at /home/vitor/Projetos/pathseg/pathseg.js:316:30
    at Object.<anonymous> (/home/vitor/Projetos/pathseg/pathseg.js:844:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at [eval]:1:14
```

I'm not sure if this bug existed before, but I'd guess yes, as there was a similar bug fixed by https://github.com/progers/pathseg/commit/be4ff0dd7675f0221b726485f68af2565410ac99.

**Comment by progers** [comment]
Sorry for taking so long to get back to this.

I wrote a quick patch that fixes this for node but I'm left wondering how the pathseg.js polyfill would be useful without an SVGPathElement object. Can you help me understand your usecase?

**Comment by progers** [comment]
I'm going to close this for now to clean up the open issues on this project. If there's a common usecase for this, I'm definitely open to fixing it, but I think this may just be an issue for folks using pathseg.js in synthetic testing environments.
