### ISSUE TITLE
Console error on init

### ISSUE THREAD

**Issue by nicolasd** [progers/pathseg#2]
On SVGEdit init i have this kind of error in the JS console:

Error: Invalid value for <path> attribute d="L 5 5 L 10 10"
SVGPathSegList._writeListToPath	@	pathseg.js:386
SVGPathSegList.replaceItem	@	pathseg.js:452

Error: Invalid value for <path> attribute d="L 5 5 M 0 0 L 10 10"
SVGPathSegList._writeListToPath @ pathseg.js:386
SVGPathSegList.insertItemBefore @ pathseg.js:438

**Comment by NaxYo** [comment]
+1

Workaround on line 492?:
```javascript
string += pathSeg._asPathString().replace(/^L/, 'M');
```
It seems to work for now

**Comment by progers** [comment]
Thanks for taking the time to report this. Looks like Jeff got it in https://github.com/SVG-Edit/svgedit/commit/948ba30214d9fe735e4f48e129b40ddefd03103f
