### ISSUE TITLE
Android 5.0 webview

### ISSUE THREAD

**Issue by ZGhekuiwu** [progers/pathseg#21]
Is not supported on Android 5.0 webview?

**Comment by progers** [comment]
I don't have an Android 5.0 webview to test with but I think it should work there. In older versions of chrome, before SVGPathSeg was removed, this library should do nothing and the existing implementation should be used automatically. You can test this by running the tests in Android 5.0 webview. If that's not the case, please file a bug with exactly what breaks.

**Comment by ZGhekuiwu** [comment]
Sorry, I use the version is too low ... After the update pathseg.js no problem.

**Comment by progers** [comment]
Ok cool, glad to hear it's all working.
