### ISSUE TITLE
Fails on Chrome 62

### ISSUE THREAD

**Issue by liabru** [progers/pathseg#22]
I've had this polyfill working great up until the release of Chrome 62 and above where it no longer works, giving the error message:

```
 Uncaught TypeError: path.getPathSegAtLength is not a function
 at Object.Svg.pathToVertices (matter-dev.js:7523)
 at SVGPathElement.<anonymous> (Examples.js:14922)
```

Here is my page showing the error: http://brm.io/matter-js/demo/#terrain
(note that it's only the Terrain and Concave SVG Paths demos that use pathseg).

I've tested older versions of Chrome, plus the latest Firefox and Safari and they work fine.

Thank you for your work!

**Comment by progers** [comment]
Hi @liabru , sorry about the long delay, I've been offline caring for a newborn.

It looks like you are using an older version of pathseg.js:
http://brm.io/matter-js/demo/js/lib/pathseg.js

The latest version added support for path.getPathSegAtLength:
https://github.com/progers/pathseg/blob/master/pathseg.js#L336

You should be able to just replace your version of pathseg.js with the latest one (i.e., it should be a drop-in replacement).

I'm going to close this issue but please do comment & reopen if something doesn't work.

**Comment by liabru** [comment]
No problem (and congrats!). Sorry I didn't expect that you had patched the missing `getPathSegAtLength` before it got removed, so I'll try updating my version. Thanks for looking into it!
