### ISSUE TITLE
Firefox 59 is not compatible with the polyfill

### ISSUE THREAD

**Issue by jwatt** [progers/pathseg#23]
Firefox 59 (currently in beta) doesn't work with the polyfill. As of that Firefox version, all the API that can be used to mutate an SVGPathSegList (along with any API that can be used to create SVGPathSeg type objects) was removed:

https://hg.mozilla.org/releases/mozilla-beta/rev/a9062e1bafb7

There are reasons for this awkward partial-removal, but suffice it to say here that it means Firefox is annoyingly incompatible with this polyfill.

I should create a pull request so the polyfill will work in Firefox, but I'm not sure when I'll get to that. I'm filing this issue in case someone can get to it before me.

If anyone does work on this, please comment here first so we don't duplicate work (I'll do the same).

**Comment by progers** [comment]
Thank you for taking the time to file this!

**Comment by progers** [comment]
I think I understand what was removed in that patch, and I think it can be polyfilled. I'll start working on a patch to pathseg.js now for firefox 59+ support.

Higher-level question: I'm also a browser developer and helped remove the path seg API from chromium (credit where it's due, I believe @fsoder wrote the actual removal patch). It was rough breaking so many pages which led me to make this polyfill. This removal from Gecko will partially break all of those users again, most of which likely switched to this library. For example, svg-edit now throws "TypeError: u.clear is not a function" when editing a path in Firefox (see: svgedit.com). I wonder if it would be easier to remove the path seg API wholesale in the interest of web compatiblity?

**Comment by jwatt** [comment]
> I'll start working on a patch to pathseg.js now for firefox 59+ support.

That'd be awesome, thank you!

> I wonder if it would be easier to remove the path seg API wholesale in the interest of web compatiblity?

It definitely would have been the prefered option. The issue that came up that prevented doing that was that Blink has changed behavior so that SMIL animations affect attribute values. Removing the entire API (specifically SVGPathElement.d.animVal) would have meant that developers would have no longer had any way to get access to the animated values of path data. It probably makes sense for Firefox to match Blink's behavior, but that's a big change and may need some reverse engineering or other work to figure out what exactly the behavior is. It wasn't something that could be done in the timescale that required us to make the API immutable.

**Comment by progers** [comment]
Sounds good! These APIs are complex and changing them seems to always have those sorts of tradeoffs :/

The latest commit should fix everything in pathseg.js for Firefox, and I've filed https://github.com/SVG-Edit/svgedit/issues/216 to fix svgedit.

**Comment by fsoder** [comment]
Late to the party but... incidentally I think the same thing may prevent us (Blink) from fixing the attribute syncing behavior... (not entirely trivial to use-counter efficiently either I'd think.) The 'd' property would work somewhat for reading the animated path though.

**Comment by progers** [comment]
@fsoder, can you help me understand what you mean about the attribute syncing behavior being broken in blink? Do you mean how the 'd' property in particular doesn't work like x, y, width, height, etc, in terms of being an animated presentation attribute? For example, I don't think there is a way to get the non-animated (base) 'd' value if there's an active animation. Or do you mean something more general about attribute syncing?

**Comment by fsoder** [comment]
I meant the thing thst @jwatt mentioned - that (SMIL) animations affect attribute values. (This is essentially the same as not being able to get the base attribute value, if any, while an animation is applied. Only with different negative connotations.) I took advantage of this when adjusting some tests before the removal of the path seg interfaces. Maybe these tests made it into WPT in that form. (FWIW, https://bugs.chromium.org/p/chromium/issues/detail?id=735820 is a bug related to this.)
