### ISSUE TITLE
Firefox issues

### ISSUE THREAD

**Issue by Laukku** [progers/pathseg#25]
Now that the latest version of Firefox also did the dum-dumb and removed the path functionality, I tested your polyfill in my little pet svg project. I get this error: 
`TypeError: path.pathSegList[0] is undefined`

When I try to alter the pathSegList to move a path like this:
`path.pathSegList[0].x = point.x;`

This used to work. Console.logging path.pathSegList looks like this:
`Object { _pathElement: path#middlep, _list: […], _mutationObserverConfig: {…}, _pathElementMutationObserver: MutationObserver }`

This is what it looks like when it works correctly:
`SVGPathSegList [ SVGPathSegMovetoRel, SVGPathSegLinetoRel, SVGPathSegCurvetoCubicRel, SVGPathSegCurvetoCubicRel ]`

In fact, it seems that on the second time I use something covered by the polyfill, this happens.

I don't feel like making a minimal example, but luckily this example by someone else also breaks in a similar manner: [SGV rel to abs by kirkerafael](https://embed.plnkr.co/a4GIp0/). I get this error: 
```
TypeError: segs.replaceItem is not a function[Learn More]	script.js:20:19
convertToAbsolute	https://run.plnkr.co/preview/cjevsn2os0007fillmjvzbyqv/script.js:20:19
convert		https://run.plnkr.co/preview/cjevsn2os0007fillmjvzbyqv/script.js:43:3
onclick		https://run.plnkr.co/preview/cjevsn2os0007fillmjvzbyqv/:1:1
```
I wonder if there's an easy fix that would make us Firefox users also benefit from your polyfill.

**Comment by progers** [comment]
Thanks for taking the time to file a bug.

This should work as of https://github.com/progers/pathseg/pull/24. Are you using the latest version of pathseg.js? I checked the linked example by kirkerafael and they seem to be using an older copy.

Try updating your copy of pathseg.js and see if this works again.

**Comment by Laukku** [comment]
Thanks, updating seems to fix the problem on that plunk. but not in my script, where I was already using the newest version. To make my script work I seem to need to change every instance of accessing the pathSegList from e.g.:
`var seglist = path.pathSegList;`
to:
```
if (path.pathSegList._list === undefined){
	console.log("in getpoints", path.pathSegList);
	var seglist = path.pathSegList;
} else if (path.pathSegList._list !== undefined){
	console.log("in getpoints, needs ._list", path.pathSegList._list);
	var seglist = path.pathSegList._list;
}
```
For some reason, sometimes pathSegList is a SVGPathSegList, sometimes an object that has a _list property that can be used like a pathseglist.

**Comment by progers** [comment]
Can you create a small, minimal plunkr (or jsbin) example that used to work in Firefox 58 but no longer does in Firefox 59? I can take a look ASAP in case other folks will hit the same issue.

You shouldn't really access _list at all, as that's supposed to be hidden. The underscore is intended to mean "private", although it's javascript so you can always poke at it.

**Comment by Laukku** [comment]
Here you go: [plunk](http://plnkr.co/edit/MW8KhZ1vXGJ11ky54Lo1) This again says `TypeError: path.pathSegList[0] is undefined` if I include your polyfill. Otherwise it works. I'm not using any of the segment creation methods here though, which I also employ a lot in my project.

I know _ means no touchy but it was the only thing that worked, and I figured it might help you to see what's happening.

**Comment by progers** [comment]
@Laukku, thank you for that small testcase!

The issue is that Firefox allowed array access into the list whereas WebKit/Safari and Blink/Chromium do not. For example, this worked but only in Firefox:
```
var path = document.createElementNS("http://www.w3.org/2000/svg", "path");
path.setAttribute("d", "M50 51Z");
assert.equal(path.pathSegList[0].toString(), "[object SVGPathSegMovetoAbs]");
```

As far as I can tell, this was a quirk of Firefox's implementation and was not actually specified. I don't mean that you were wrong to depend on it, just that it was a bug that Firefox supported it at all. It's possible to implement this in the polyfill but it requires ES6 features and is pretty complicated. Because this only worked in Firefox and is complicated to polyfill, I'm leaning towards not polyfilling this.

Is it an option for you to update your code to use: `path.pathSegList.getItem(0)` instead of `path.pathSegList[0]`?

**Comment by Laukku** [comment]
Since I'm the only user of my little project, I never even tested other browsers! Yeah, I can live with getItem(), now that I know that it will work. Thanks!

**Comment by progers** [comment]
Thanks again for taking the time to file this. I'll close as for now, but if I get other reports of this same issue, I'll reopen it.
