### ISSUE TITLE
Proper license

### ISSUE THREAD

**Issue by brettz9** [progers/pathseg#29]
Hi,

The `license` field present in `package.json`, i.e., "Chromium's License", is not a standard SPDX identifier, so it can cause license analysis tools to break. Can you update this?

[Wikipedia's article](https://en.wikipedia.org/wiki/Chromium_(web_browser)#Licensing) links to https://web.archive.org/web/20081026150300/http://code.google.com/chromium/terms.html for the assorted licenses it is under so one could create a parenthesized "AND" expression like "(BSD-3-Clause AND MIT AND ...)". IANAL, but I wonder whether you really need to use that if you were merely adapting non-JavaScript source code for JavaScript.

Thanks!

**Comment by progers** [comment]
I spent a few minutes searching and didn't find the SPDX identifier for Chromium's license. Do you know if a standard one exists? I'd be happy to include it.

The javascript code is actually a copy of the original C++ in Chromium (essentially started with the .cc file renamed to .js). I think the original license is maintained that situation. I'd be happy to change this if possible but it seems pretty clear to me that this is still Chromium code (with all the unfortunate baggage that includes).
