### ISSUE TITLE
Polyfill Throws in a Server-Side Rendering (SSR) Environment

### ISSUE THREAD

**Issue by gregjacobs** [progers/pathseg#30]
Hey @progers,

My application is currently consuming a library which relies on the pathseg polyfill (thanks so much for this polyfill btw!)

We're a React app and have a requirement to enable server-side rendering on our end. Unfortunately, importing the pathseg polyfill results in an error being thrown for `window` being undefined in the server-side environment. 

A quick one-liner can be added to make the polyfill compatible in a DOM-less SSR environment like `react-dom/server`'s. This would be placed as the first line inside the IIFE:

```ts
(function() { "use strict";
    if (typeof window === 'undefined') return;

    // ... rest of code here ...
}());
```

I can create a quick PR if needed?

Thanks!
Greg

**Comment by progers** [comment]
If there is no window object, what effect does this polyfill have, since the purpose of this code is to add things to the window object? Can you instead not include the polyfill in your SSR environment?

**Comment by gregjacobs** [comment]
So unfortunately no, we can't only include the polyfill on the browser and exclude it from the server. Not sure if you're familiar with SSR rendering a React app with a tool like Next.js or Gatsby, but the same JS code that goes to the client browser is also what goes through the server to server-render an HTML page. Because it's the same JS bundle, we basically we can't do a conditional import:

```ts
if (typeof window !== 'undefined') {
    import 'pathseg';  // <-- nope: imports must exist at the top level
}
```

**Comment by progers** [comment]
The purpose of this library is just to add some global objects. Is there a way to structure a library like this one so that it'll actually work in all environments, rather than stubbing itself out?

I am not very familiar with this area and am open to being wrong. Are you asking every client-side javascript library using browser APIs (`window`, canvas, etc) to add a SSR-specific special-case? Is there precedent for other client-side javascript libraries adding SSR workarounds like this? If you want the behavior of this library running but doing nothing server-side, could you just declare a dummy window (like `global.window = {};`)?

**Comment by gregjacobs** [comment]
Hey Phillip,

Thanks for getting back to me, and for the timely responses! Really appreciate that.

So client-side libraries (dependencies) generally must handle the SSR environment case themselves because the code which relies on browser globals can't be selectively removed by the consuming app. With the popularity of React and the rise of server-side rendering for SEO and fast initial page loads, I would say most libraries are doing this these days.

Some examples of popular libraries out in the wild:
- **flatpickr** (a vanilla JS datepicker): https://github.com/flatpickr/flatpickr/blob/a66718aa20b69bae33038f16d0b22446f8ab5e30/src/index.ts#L2930
- **Emotion** (CSS-in-JS library): https://github.com/emotion-js/emotion/blob/v10.0.6/packages/cache/src/index.js#L9. They use this `isBrowser` flag across the code in that file
- **HighCharts**: https://github.com/highcharts/highcharts/blob/v9.1.2/ts/Core/Globals.ts#L105. This project sets a variable which normalizes `window` to an empty object for non-browser environments, and then uses that variable across the codebase
- **ag-Grid**: https://github.com/ag-grid/ag-grid/blob/93841bb029bbafe2600a7559e27ac393575152c8/grid-packages/ag-grid-docs/documentation/src/utils/is-server-side-rendering.js. Aptly-named file: `is-server-side-rendering.js` 🙂 

Unfortunately, declaring a dummy `global.window = {}` might actually _break_ some of these libraries which rely on `window`'s existence to know when they are in a server-side vs. browser environment. They may then try to access properties of the `window` object that are undefined which would result in runtime errors.

I don't think there's another option to be able to be able to support SSR when importing a library that depends on pathseg. Even if the library itself could implement a conditional workaround, that would mean that _all_ libraries which import pathseg would also need that same workaround.

Thoughts?

**Comment by progers** [comment]
Thanks for your detailed reply. I agree that it makes sense to check for a browser environment in this library. Can you send me a PR?

Can you include a simple comment? I'm thinking something like the following (feel free to improve it):
```
(function() { "use strict";
    // This polyfill only applies to browser environments with a window object (e.g., not node.js, workers, etc).
    if (typeof window === 'undefined')
        return;
...
```

**Comment by gregjacobs** [comment]
Sounds good, will do! I'm on my work laptop right now (which sadly blocks pushing to GitHub), but I'll submit a PR when I get home tonight. 

Thanks!

**Comment by gregjacobs** [comment]
Hey, created PR https://github.com/progers/pathseg/pull/31
