### ISSUE TITLE
Performance issues with getPathSegAtLength

### ISSUE THREAD

**Issue by el1s7** [progers/pathseg#34]
I've been stressing out trying to convert a SVG path element to a vertex format compatible with [matter-js](https://github.com/liabru/matter-js) which makes use of this polyfill. 

After spending a few good hours, I managed to get it working, however I noticed the browser gets always freezed for a few seconds and I found out that **getPathSegAtLength** is causing this.

Calling **getPathSegAtLength** on a loop with more 1000 items is slow and freezes the browser. See the code of matter-js [here](https://github.com/liabru/matter-js/blob/081645474c4aa798e5b1ede5d5230b0ecb8835d2/src/geometry/Svg.js) 

Any ideas on how to optimize the function or prevent it from freezing the browser?
I tried web workers but they don't work with DOM elements

**Comment by el1s7** [comment]
I ended up using a chunked function wrapper with `setTimeout` and promises to process the path points slowly but without freezing the browser.

**Comment by progers** [comment]
This code hasn't really been profiled before, as it's just a port of c++ code. If you have a simple testcase, I can take a look. In general, your approach of chunking is a good idea for expensive work on the ui/main thread.

I'll close this issue for now but I'm happy to reopen if there's something actionable for this library.
