### ISSUE TITLE
Requesting a release

### ISSUE THREAD

**Issue by spadgett** [progers/pathseg#9]
We'd like to reference a particular version of pathseg in brower.json for repeatable builds in our project.

/cc @jwforres

**Comment by progers** [comment]
I'm a bower beginner and only added bower.json for everyone else :) Can you point me at instructions for doing this, or submit a pull request?

**Comment by jwforres** [comment]
in github create a semver tag, http://semver.org/
example "v1.0.0"

any time you push updates you should bump the last number (patch) if its a fix that doesnt affect backward compatabillity, more significant changes should bump the minor version or the major version.  Also the version in your bower.json file needs to match the semver tag.  So if you are going to add a new release you would include a bump in version number in bower.json as part of that commit.

**Comment by jwforres** [comment]
here is one of our bower repos as an example https://github.com/kubernetes-ui/label-selector/releases

**Comment by progers** [comment]
Thank you both!

After some initial confusion about ordering, I've created the first real release: https://github.com/progers/pathseg/releases/tag/v1.0.2

I don't expect many changes to pathseg going forward and it shouldn't be a problem to keep the versions up to date for the occasional change. Could you please double-check that v1.0.2 is setup properly?

**Comment by spadgett** [comment]
:+1: Works great. Thank you!
